baseURL = "https://abapinho.com/"
languageCode = "pt-PT"
title = "Abapinho"
author = "Nuno Godinho"
defaultContentLanguage = "pt"
theme = "abapinho_v1"
copyright = "&copy;2009-2020 Nuno Godinho"
paginate = 15
refLinksErrorLevel = "WARNING"

[permalinks]
posts = "/:year/:month/:title/"

[params]
description = "ABAP em português"
keywords = "ABAP, SAP, IDOC, IDOCS, BAPI, BADI, user-exit, user-exits, enhancements, dicas, artigos"

[languages.pt]
languageName = "Português"
weight = 1

[languages.en]
languageName = "English"
weight = 2
