baseURL = "https://v2.abapinho.com/"
languageCode = "pt-PT"
title = "Abapinho"
author = "Nuno Godinho"
defaultContentLanguage = "pt"
theme = "abapinho_v1"
copyright = "&copy;2009-2022 Nuno Godinho"
paginate = 15
refLinksErrorLevel = "WARNING"

[permalinks]
posts = "/:year/:month/:slug/"

[params]
description = "ABAP em português"
keywords = "ABAP, SAP, IDOC, IDOCS, BAPI, BADI, user-exit, user-exits, enhancements, dicas, artigos"

[outputs]
home = [ "HTML",]

[languages.pt]
languageName = "Português"
weight = 1

[languages.en]
languageName = "English"
weight = 2

[languages.pt.menu]
[[languages.pt.menu.main]]
name = "Dicas"
url = "/categories/dicas/"
weight = 10

[[languages.pt.menu.main]]
name = "Artigos"
url = "/categories/artigos/"
weight = 20

[[languages.pt.menu.main]]
name = "Boas prácticas"
url = "/categories/boaspracticas/"
weight = 30

[[languages.pt.menu.main]]
name = "Histórias"
url = "/categories/historias/"
weight = 40

[[languages.pt.menu.main]]
name = "Notícias"
url = "/categories/noticias/"
weight = 50

[[languages.pt.menu.main]]
name = "Código"
url = "/categories/codigo/"
weight = 60

[languages.en.menu]
[[languages.en.menu.main]]
name = "Tips&Tricks"
url = "/categories/dicas/"
weight = 10

[[languages.en.menu.main]]
name = "Articles"
url = "/categories/artigos/"
weight = 20

[[languages.en.menu.main]]
name = "Best practices"
url = "/categories/boaspracticas/"
weight = 30

[[languages.en.menu.main]]
name = "Stories"
url = "/categories/historias/"
weight = 40

[[languages.en.menu.main]]
name = "News"
url = "/categories/noticias/"
weight = 50

[[languages.en.menu.main]]
name = "Code"
url = "/categories/codigo/"
weight = 60
