baseURL = "https://abapinho.com/"
languageCode = "pt-PT"
title = "Abapinho"
defaultContentLanguage = "pt"
# theme = "hugo-notepadium"
# theme = "aether"
theme = "abapinho_v1"
refLinksErrorLevel = "WARNING"

[params]
  description = "ABAP em português"
  copyright = "&copy;2009-2020 Nuno Godinho"

[languages]
  [languages.pt]
    languageName = "Português"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
