[[redirects]]
from = "/*"
to = "/en/:splat"
status = 301
force = false

[redirects.query]
path = ":path"
[redirects.conditions]
Language = [ "en",]
[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "0"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.2"
