[[redirects]]
from = "/*"
to = "/en/:splat"
status = 301
force = false

[redirects.query]
path = ":path"
[redirects.conditions]
Language = [ "en",]
[[plugins]]
package = "@algolia/netlify-plugin-crawler"

[plugins.inputs]
branches = [ "*",]

[build]
publish = "public"
command = "./netlify_build.sh"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.2"
