[build]
publish = "public"
command = "./netlify_build.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.2"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[functions]
directory = "netlify/functions"

[functions.call-build-hook]
schedule = "5 9 * * *"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "0"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "default-src 'self' abapinho.com *.abapinho.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/npm/@algolia/autocomplete-theme-classic; form-action 'self'; script-src 'self' 'unsafe-inline' abapinho.com *.abapinho.com https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js algolianet.com *.algolianet.com; connect-src 'self' abapinho.com *.abapinho.com algolianet.com *.algolianet.com *.algolia.net; img-src 'self'; base-uri 'self';"
Referrer-Policy = "no-referrer"

[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
debug = false

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
output_path = "reports/lighthouse.html"

[[plugins]]
package = "netlify-plugin-no-more-404"

[plugins.inputs]
on404 = "warn"
cacheKey = "20220121"

[[redirects]]
from = "/*"
to = "/en/:splat"
status = 301
force = false

[redirects.conditions]
Language = [ "en",]

[redirects.query]
path = ":path"
