[[redirects]]
from = "/*"
to = "/en/:splat"
status = 301
force = false

[redirects.query]
path = ":path"
[redirects.conditions]
Language = [ "en",]
[[plugins]]
package = "@algolia/netlify-plugin-crawler"

[plugins.inputs]
branches = [ "*",]

[build]
publish = "public"
command = "hugo"
